//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMMP_utils.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMMP_utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_abt {
            get {
                return ResourceManager.GetString("home_abt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © minotto 2025. All rights reserved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_abt_info_desc {
            get {
                return ResourceManager.GetString("home_abt_info_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YMMP-utils に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_abt_info_header {
            get {
                return ResourceManager.GetString("home_abt_info_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of useless tools for YMM4/YMMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_header_desc {
            get {
                return ResourceManager.GetString("home_header_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YMMP-utils に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_header_title {
            get {
                return ResourceManager.GetString("home_header_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some parts of background scripts are written by LLM. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_LLM {
            get {
                return ResourceManager.GetString("home_LLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg {
            get {
                return ResourceManager.GetString("home_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change display language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_lang_desc {
            get {
                return ResourceManager.GetString("home_stg_lang_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_lang_header {
            get {
                return ResourceManager.GetString("home_stg_lang_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path of YMM4 execution program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_path_desc {
            get {
                return ResourceManager.GetString("home_stg_path_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YMM4 Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_path_header {
            get {
                return ResourceManager.GetString("home_stg_path_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_upd_btn {
            get {
                return ResourceManager.GetString("home_stg_upd_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for updates from GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_upd_desc {
            get {
                return ResourceManager.GetString("home_stg_upd_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_stg_upd_header {
            get {
                return ResourceManager.GetString("home_stg_upd_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPPtoYMMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string nav_convert {
            get {
                return ResourceManager.GetString("nav_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string nav_home {
            get {
                return ResourceManager.GetString("nav_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string nav_tools {
            get {
                return ResourceManager.GetString("nav_tools", resourceCulture);
            }
        }
    }
}
